[package]
name = "monarch"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
# Tauri dependencies
tauri = { version = "1.2", features = ["dialog-open", "fs-read-file", "protocol-asset", "shell-open", "window-set-min-size"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Monarch dependencies
tokio = { version = "1", features = ["full"] }
winreg = "0.10.1"
reqwest = "0.11.0"
scraper = "0.15.0"
log = "0.4.17"
log4rs = "1.2.0"
image = "0.24.6"
json = "0.12.4"
vdf = "0.1.0"
vdf-serde = "0.3.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
