[package]
name = "Monarch"
version = "0.0.1"
description = "A FOSS game launcher targeting Windows."
authors = ["an0nymoos3", "Dre-Van-den-Hooff"]
license = ""
repository = "https://github.com/an0nymoos3/Monarch"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
# Tauri dependencies
tauri = { version = "1.2", features = ["dialog-ask", "dialog-confirm", "dialog-message", "dialog-open", "fs-read-file", "protocol-asset", "shell-open", "window-set-min-size"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Monarch dependencies
tokio = { version = "1", features = ["full"] }
winreg = "0.10.1"
reqwest = "0.11.0"
scraper = "0.15.0"
log = "0.4.17"
log4rs = "1.2.0"
regex = "1.8.1"
image = "0.24.6"
vdf-serde = "0.3.0"
rust-ini = "0.19.0"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
