use anyhow::{Context, Result};
use sqlx::{Decode, Encode, FromRow, SqlitePool};

use crate::monarch_games::monarchgame::{MonarchGame, MonarchGameProperties, StoreInfo};

const MONARCH_GAME_FIELDS: &'static str = "(name, id, executable_path, thumbnail_path, thumbnail_url, launch_args, compatibilty, summary, artwork_path, artwork_url, imported)";
const TYPED_MONARCH_GAME_FIELDS: &'static str = "(name TEXT, id TEXT, executable_path TEXT, thumbnail_path TEXT, thumbnail_url TEXT, launch_args TEXT, compatibilty TEXT, summary TEXT, artwork_path TEXT, artwork_url TEXT, imported TEXT)";

const STORE_INFO_FIELDS: &'static str = "(monarch_game_id, name, store_id, store_url)";
const TYPED_STORE_INFO_FIELDS: &'static str =
    "(monarch_game_id TEXT, name TEXT, store_id TEXT, store_url TEXT)";

const MONARCH_GAME_PROPERTIES_FIELDS: &'static str = "(monarch_game_id, install_dir, size_on_disk, last_played, time_played, description, version, protondb_rating, protondb_url)";
const TYPED_MONARCH_GAME_PROPERTIES_FIELDS: &'static str = "(monarch_game_id TEXT, install_dir TEXT, size_on_disk TEXT, last_played TEXT, time_played TEXT, description TEXT, version TEXT, protondb_rating TEXT, protondb_url TEXT)";

#[derive(Debug, FromRow, Encode, Decode)]
struct MonarchGameRecord {
    pub name: String,
    pub id: String, // Monach ID, generated by monarch-launcher.com
    pub executable_path: Option<String>,
    pub thumbnail_path: String,
    pub thumbnail_url: String,
    pub launch_args: Option<String>,
    pub compatibility: Option<String>,
    pub summary: String,
    pub artwork_path: String,
    pub artwork_url: String,
    pub imported: bool,
}

#[derive(Debug, FromRow, Encode, Decode)]
struct StoreInfoRecord {
    pub monarch_game_id: String,
    pub name: String,
    pub store_id: String,
    pub store_url: String,
}

#[derive(Debug, FromRow, Encode, Decode)]
struct MonarchGamePropertiesRecord {
    pub monarch_game_id: String,
    pub install_dir: String,
    pub size_on_disk: u64,
    pub last_played: String,
    pub time_played: String,
    pub description: String,
    pub version: String,

    pub protondb_rating: String,
    pub protondb_url: String,
}

impl MonarchGame {
    fn from_sql(
        game_record: MonarchGameRecord,
        store_records: Vec<StoreInfoRecord>,
        properties_record: MonarchGamePropertiesRecord,
    ) -> Self {
        let stores: Vec<StoreInfo> = store_records
            .into_iter()
            .map(|sir| sir.into())
            .collect::<Vec<StoreInfo>>();

        let properties: MonarchGameProperties = properties_record.into();

        Self {
            name: game_record.name,
            id: game_record.id,
            stores,
            executable_path: game_record.executable_path,
            thumbnail_path: game_record.thumbnail_path,
            thumbnail_url: game_record.thumbnail_url,
            launch_args: game_record.launch_args,
            compatibility: game_record.compatibility,
            summary: game_record.summary,
            artwork_path: game_record.artwork_path,
            artwork_url: game_record.artwork_url,
            properties,
            imported: game_record.imported,
        }
    }
}

impl From<StoreInfoRecord> for StoreInfo {
    fn from(record: StoreInfoRecord) -> Self {
        Self {
            name: record.name,
            store_id: record.store_id,
            store_url: record.store_url,
        }
    }
}

impl From<MonarchGamePropertiesRecord> for MonarchGameProperties {
    fn from(record: MonarchGamePropertiesRecord) -> Self {
        Self {
            install_dir: record.install_dir,
            size_on_disk: record.size_on_disk,
            last_played: record.last_played,
            time_played: record.time_played,
            description: record.description,
            version: record.version,
            protondb_rating: record.protondb_rating,
            protondb_url: record.protondb_url,
        }
    }
}

/// Fetch all games stores in db, including their properties and storefronts
pub async fn get_library(pool: &SqlitePool) -> Result<Vec<MonarchGame>> {
    // Using the macro enables compile-time stuff

    // TODO: Redo stores and propeties with batched request?

    let game_records: Vec<MonarchGameRecord> =
        sqlx::query_as::<_, MonarchGameRecord>("SELECT * FROM library")
            .fetch_all(pool)
            .await
            .with_context(|| {
                "monarch_sql::get_library() Failed to fetch_all() MonarchGameRecords! | Err: "
            })?;

    let mut games: Vec<MonarchGame> = Vec::new();
    for game in game_records {
        let stores: Vec<StoreInfoRecord> =
            sqlx::query_as("SELECT * FROM stores WHERE monarch_game_id = ?")
                .bind(&game.id)
                .fetch_all(pool)
                .await
                .with_context(|| {
                    format!(
                        "monarch_sql::get_library() Failed to query StoreInfo for {} | Err: ",
                        &game.name
                    )
                })?;

        let properties: MonarchGamePropertiesRecord =
            sqlx::query_as("SELECT * FROM properties WHERE monarch_game_id = ?")
                .bind(&game.id)
                .fetch_one(pool)
                .await
                .with_context(|| {
                    format!(
                "monarch_sql::get_library() Failed to query MonarchGameProperties for {} | Err: ",
                &game.name
            )
                })?;

        games.push(MonarchGame::from_sql(game, stores, properties));
    }

    Ok(games)
}

pub async fn insert_game(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::insert_game() Failed to start new transaction! | Err: ")?;

    sqlx::query(&format!("INSERT INTO library {}", MONARCH_GAME_FIELDS))
        .bind(&game.name)
        .bind(&game.id)
        .bind(&game.executable_path)
        .bind(&game.thumbnail_path)
        .bind(&game.thumbnail_url)
        .bind(&game.launch_args)
        .bind(&game.compatibility)
        .bind(&game.summary)
        .bind(&game.artwork_path)
        .bind(&game.artwork_url)
        .bind(game.imported)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            "monarch_sql::insert_game() Failed to insert game into library! | Err: "
        })?;

    sqlx::query(&format!("INSERT INTO stores {}", STORE_INFO_FIELDS))
        .execute(&mut *tx)
        .await
        .with_context(|| {
            "monarch_sql::insert_game() Failed to insert game into library! | Err: "
        })?;

    sqlx::query(&format!(
        "INSERT INTO properties {}",
        MONARCH_GAME_PROPERTIES_FIELDS
    ))
    .execute(&mut *tx)
    .await
    .with_context(|| "monarch_sql::insert_game() Failed to insert game into library! | Err: ")?;

    tx.commit()
        .await
        .with_context(|| "monarch_sql::insert_game() Failed to commit transaction! | Err: ")
}

/// Remove all records of a game, including its properties and storefronts
pub async fn remove_game(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::remove_game() Failed to start new transaction! | Err: ")?;

    sqlx::query("DELETE FROM library WHERE id = ?")
        .bind(&game.id)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::remove_game() Failed to remove {} from library table! | Err: ",
                &game.name
            )
        })?;

    sqlx::query("DELETE FROM stores WHERE monarch_game_id = ?")
        .bind(&game.id)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::remove_game() Failed to remove {} from stores table! | Err: ",
                &game.name
            )
        })?;

    sqlx::query("DELETE FROM properties WHERE monarch_game_id = ?")
        .bind(&game.id)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::remove_game() Failed to remove {} from properties table! | Err: ",
                &game.name
            )
        })?;

    tx.commit()
        .await
        .with_context(|| "monarch_sql::remove_game() Failed to commit transaction! | Err: ")
}

/// Update game in db.
pub async fn update_game(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    // TODO: Write logic for handling inserting or upserting
    // Likely using something akin to INSERT [...] ON CONFLICT [...]
    Ok(())
}

/// Initiates db, which ensures all tables exist or are created
/// on application launch.
pub async fn init_db(pool: &SqlitePool) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::init_db() Failed to start transaction! | Err: ")?;

    sqlx::query(&format!(
        "CREATE TABLE IF NOT EXISTS library {}",
        TYPED_MONARCH_GAME_FIELDS
    ))
    .execute(&mut *tx)
    .await
    .with_context(|| "monarch_sql::init_db() Failed to verify library table! | Err: ")?;

    sqlx::query(&format!(
        "CREATE TABLE IF NOT EXISTS stores {}",
        TYPED_STORE_INFO_FIELDS
    ))
    .execute(&mut *tx)
    .await
    .with_context(|| "monarch_sql::init_db() Failed to verify stores table! | Err: ")?;

    sqlx::query(&format!(
        "CREATE TABLE IF NOT EXISTS properties {}",
        TYPED_MONARCH_GAME_PROPERTIES_FIELDS
    ))
    .execute(&mut *tx)
    .await
    .with_context(|| "monarch_sql::init_db() Failed to verify properties table! | Err: ")?;

    tx.commit()
        .await
        .with_context(|| "monarch_sql::init_db() Failed to commit transaction | Err: ")
}
