use anyhow::{Context, Result};
use sqlx::{Decode, Encode, FromRow, SqlitePool};
use tracing::warn;

use crate::monarch_games::monarchgame::{MonarchGame, MonarchGameProperties, StoreInfo};

const MONARCH_GAME_FIELDS: &str = "(name, id, executable_path, thumbnail_path, thumbnail_url, launch_args, compatibility, summary, artwork_path, artwork_url, imported)";
const TYPED_MONARCH_GAME_FIELDS: &str = "(name TEXT, id TEXT PRIMARY KEY, executable_path TEXT, thumbnail_path TEXT, thumbnail_url TEXT, launch_args TEXT, compatibility TEXT, summary TEXT, artwork_path TEXT, artwork_url TEXT, imported BOOLEAN)";

const STORE_INFO_FIELDS: &str = "(monarch_game_id, name, store_id, store_url)";
const TYPED_STORE_INFO_FIELDS: &str =
    "(monarch_game_id TEXT PRIMARY KEY, name TEXT, store_id TEXT, store_url TEXT)";

const MONARCH_GAME_PROPERTIES_FIELDS: &str = "(monarch_game_id, install_dir, size_on_disk, last_played, time_played, description, version, protondb_rating, protondb_url)";
const TYPED_MONARCH_GAME_PROPERTIES_FIELDS: &str = "(monarch_game_id TEXT PRIMARY KEY, install_dir TEXT, size_on_disk INTEGER, last_played TEXT, time_played TEXT, description TEXT, version TEXT, protondb_rating TEXT, protondb_url TEXT)";

#[derive(Debug, FromRow, Encode, Decode)]
struct MonarchGameRecord {
    pub name: String,
    pub id: String, // Monach ID, generated by monarch-launcher.com
    pub executable_path: Option<String>,
    pub thumbnail_path: String,
    pub thumbnail_url: String,
    pub launch_args: Option<String>,
    pub compatibility: Option<String>,
    pub summary: String,
    pub artwork_path: String,
    pub artwork_url: String,
    pub imported: bool,
}

#[derive(Debug, FromRow, Encode, Decode)]
struct StoreInfoRecord {
    pub monarch_game_id: String,
    pub name: String,
    pub store_id: String,
    pub store_url: String,
}

#[derive(Debug, FromRow, Encode, Decode)]
struct MonarchGamePropertiesRecord {
    pub monarch_game_id: String,
    pub install_dir: String,
    pub size_on_disk: u64,
    pub last_played: String,
    pub time_played: String,
    pub description: String,
    pub version: String,

    pub protondb_rating: String,
    pub protondb_url: String,
}

impl MonarchGame {
    fn from_sql(
        game_record: MonarchGameRecord,
        store_records: Vec<StoreInfoRecord>,
        properties_record: MonarchGamePropertiesRecord,
    ) -> Self {
        let stores: Vec<StoreInfo> = store_records
            .into_iter()
            .map(|sir| sir.into())
            .collect::<Vec<StoreInfo>>();

        let properties: MonarchGameProperties = properties_record.into();

        Self {
            name: game_record.name,
            id: game_record.id,
            stores,
            executable_path: game_record.executable_path,
            thumbnail_path: game_record.thumbnail_path,
            thumbnail_url: game_record.thumbnail_url,
            launch_args: game_record.launch_args,
            compatibility: game_record.compatibility,
            summary: game_record.summary,
            artwork_path: game_record.artwork_path,
            artwork_url: game_record.artwork_url,
            properties,
            imported: game_record.imported,
        }
    }
}

impl From<StoreInfoRecord> for StoreInfo {
    fn from(record: StoreInfoRecord) -> Self {
        Self {
            name: record.name,
            store_id: record.store_id,
            store_url: record.store_url,
        }
    }
}

impl From<MonarchGamePropertiesRecord> for MonarchGameProperties {
    fn from(record: MonarchGamePropertiesRecord) -> Self {
        Self {
            install_dir: record.install_dir,
            size_on_disk: record.size_on_disk,
            last_played: record.last_played,
            time_played: record.time_played,
            description: record.description,
            version: record.version,
            protondb_rating: record.protondb_rating,
            protondb_url: record.protondb_url,
        }
    }
}

/// Fetch all games stores in db, including their properties and storefronts
pub async fn get_library(pool: &SqlitePool) -> Result<Vec<MonarchGame>> {
    // TODO: Use macros for compile-time checks of types/queries?

    let game_records: Vec<MonarchGameRecord> =
        sqlx::query_as::<_, MonarchGameRecord>("SELECT * FROM library")
            .fetch_all(pool)
            .await
            .with_context(|| {
                "monarch_sql::get_library() Failed to fetch_all() MonarchGameRecords! | Err: "
            })?;

    let mut games: Vec<MonarchGame> = Vec::new();
    for game in game_records {
        let stores: Vec<StoreInfoRecord> =
            sqlx::query_as("SELECT * FROM stores WHERE monarch_game_id = ?")
                .bind(&game.id)
                .fetch_all(pool)
                .await
                .with_context(|| {
                    format!(
                        "monarch_sql::get_library() Failed to query StoreInfo for {} | Err: ",
                        &game.name
                    )
                })?;

        let properties: MonarchGamePropertiesRecord =
            sqlx::query_as("SELECT * FROM properties WHERE monarch_game_id = ?")
                .bind(&game.id)
                .fetch_one(pool)
                .await
                .with_context(|| {
                    format!(
                "monarch_sql::get_library() Failed to query MonarchGameProperties for {} | Err: ",
                &game.name
            )
                })?;

        games.push(MonarchGame::from_sql(game, stores, properties));
    }

    Ok(games)
}

/// Insert a single game into the database
pub async fn insert_game(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::insert_game() Failed to start new transaction! | Err: ")?;

    sqlx::query(&format!(
        "INSERT INTO library {} VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        MONARCH_GAME_FIELDS
    ))
    .bind(&game.name)
    .bind(&game.id)
    .bind(&game.executable_path)
    .bind(&game.thumbnail_path)
    .bind(&game.thumbnail_url)
    .bind(&game.launch_args)
    .bind(&game.compatibility)
    .bind(&game.summary)
    .bind(&game.artwork_path)
    .bind(&game.artwork_url)
    .bind(game.imported)
    .execute(&mut *tx)
    .await
    .with_context(|| "monarch_sql::insert_game() Failed to insert game into library! | Err: ")?;

    for store in game.stores.iter() {
        sqlx::query(&format!(
            "INSERT INTO stores {} VALUES (?,?,?,?)",
            STORE_INFO_FIELDS
        ))
        .bind(&game.id)
        .bind(&store.name)
        .bind(&store.store_id)
        .bind(&store.store_url)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            "monarch_sql::insert_game() Failed to insert game into library! | Err: "
        })?;
    }

    sqlx::query(&format!(
        "INSERT INTO properties {} VALUES (?,?,?,?,?,?,?,?,?)",
        MONARCH_GAME_PROPERTIES_FIELDS
    ))
    .bind(&game.id)
    .bind(&game.properties.install_dir)
    .bind(game.properties.size_on_disk as u32)
    .bind(&game.properties.last_played)
    .bind(&game.properties.time_played)
    .bind(&game.properties.description)
    .bind(&game.properties.version)
    .bind(&game.properties.protondb_rating)
    .bind(&game.properties.protondb_url)
    .execute(&mut *tx)
    .await
    .with_context(|| "monarch_sql::insert_game() Failed to insert game into library! | Err: ")?;

    tx.commit()
        .await
        .with_context(|| "monarch_sql::insert_game() Failed to commit transaction! | Err: ")
}

/// Remove all records of a game, including its properties and storefronts
pub async fn remove_game(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::remove_game() Failed to start new transaction! | Err: ")?;

    sqlx::query("DELETE FROM library WHERE id = ?")
        .bind(&game.id)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::remove_game() Failed to remove {} from library table! | Err: ",
                &game.name
            )
        })?;

    sqlx::query("DELETE FROM stores WHERE monarch_game_id = ?")
        .bind(&game.id)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::remove_game() Failed to remove {} from stores table! | Err: ",
                &game.name
            )
        })?;

    sqlx::query("DELETE FROM properties WHERE monarch_game_id = ?")
        .bind(&game.id)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::remove_game() Failed to remove {} from properties table! | Err: ",
                &game.name
            )
        })?;

    tx.commit()
        .await
        .with_context(|| "monarch_sql::remove_game() Failed to commit transaction! | Err: ")
}

/// Update game in db, using Sqlite upserting
pub async fn update_game(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    let sql_library_query: String = format!(
        r#"INSERT INTO library{} 
    VALUES (?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(id) DO UPDATE SET
        name = ?,
        executable_path = ?,
        thumbnail_path = ?,
        thumbnail_url = ?,
        launch_args = ?,
        compatibility = ?,
        summary = ?,
        artwork_path = ?,
        artwork_url = ?,
        imported = ?"#,
        MONARCH_GAME_FIELDS
    );

    let sql_stores_query: String = format!(
        r#"INSERT INTO stores{} 
    VALUES (?,?,?,?)
    ON CONFLICT(monarch_game_id) DO UPDATE SET
        name = ?,
        store_id = ?,
        store_url = ?
        "#,
        STORE_INFO_FIELDS
    );

    let sql_properties_query: String = format!(
        r#"INSERT INTO properties{} 
    VALUES (?,?,?,?,?,?,?,?,?)
    ON CONFLICT(monarch_game_id) DO UPDATE SET
        install_dir = ?,
        size_on_disk = ?,
        last_played = ?,
        time_played = ?,
        description = ?,
        version = ?,
        protondb_rating = ?,
        protondb_url = ?"#,
        MONARCH_GAME_PROPERTIES_FIELDS
    );

    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::update_game() Failed to start transaction! | Err: ")?;

    sqlx::query(&sql_library_query)
        .bind(&game.name)
        .bind(&game.id)
        .bind(&game.executable_path)
        .bind(&game.thumbnail_path)
        .bind(&game.thumbnail_url)
        .bind(&game.launch_args)
        .bind(&game.compatibility)
        .bind(&game.summary)
        .bind(&game.artwork_path)
        .bind(&game.artwork_url)
        .bind(game.imported)
        .bind(&game.name)
        .bind(&game.executable_path)
        .bind(&game.thumbnail_path)
        .bind(&game.thumbnail_url)
        .bind(&game.launch_args)
        .bind(&game.compatibility)
        .bind(&game.summary)
        .bind(&game.artwork_path)
        .bind(&game.artwork_url)
        .bind(game.imported)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::update_game() Failed to upsert {} | Err: ",
                game.name
            )
        })?;

    for store in game.stores.iter() {
        sqlx::query(&sql_stores_query)
            .bind(&game.id)
            .bind(&store.name)
            .bind(&store.store_id)
            .bind(&store.store_url)
            .bind(&store.name)
            .bind(&store.store_id)
            .bind(&store.store_url)
            .execute(&mut *tx)
            .await
            .with_context(|| {
                format!(
                    "monarch_sql::update_game() Failed to upsert {} store! | Err: ",
                    game.name
                )
            })?;
    }

    sqlx::query(&sql_properties_query)
        .bind(&game.id)
        .bind(&game.properties.install_dir)
        .bind(game.properties.size_on_disk as u32)
        .bind(&game.properties.last_played)
        .bind(&game.properties.time_played)
        .bind(&game.properties.description)
        .bind(&game.properties.version)
        .bind(&game.properties.protondb_rating)
        .bind(&game.properties.protondb_url)
        .bind(&game.properties.install_dir)
        .bind(game.properties.size_on_disk as u32)
        .bind(&game.properties.last_played)
        .bind(&game.properties.time_played)
        .bind(&game.properties.description)
        .bind(&game.properties.version)
        .bind(&game.properties.protondb_rating)
        .bind(&game.properties.protondb_url)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::update_game() Failed to upsert {} properties! | Err: ",
                game.name
            )
        })?;

    tx.commit()
        .await
        .with_context(|| "monarch_sql::update_game() Failed to commit transaction! | Err: ")
}

/// Overwrite all games and it's record in the database.
/// Currently done by dropping and refilling all tables.
pub async fn overwrite_games(pool: &SqlitePool, games: &[MonarchGame]) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to start transaction! | Err: ")?;

    sqlx::query("DELETE FROM stores")
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to drop stores! | Err: ")?;

    sqlx::query("DELETE FROM properties")
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to drop properties! | Err: ")?;

    // Have to drop library last due to game.id constraint
    sqlx::query("DELETE FROM library")
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to drop library! | Err: ")?;

    for game in games {
        sqlx::query(&format!(
            "INSERT INTO library {} VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            MONARCH_GAME_FIELDS
        ))
        .bind(&game.name)
        .bind(&game.id)
        .bind(&game.executable_path)
        .bind(&game.thumbnail_path)
        .bind(&game.thumbnail_url)
        .bind(&game.launch_args)
        .bind(&game.compatibility)
        .bind(&game.summary)
        .bind(&game.artwork_path)
        .bind(&game.artwork_url)
        .bind(game.imported)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::overwrite_games() Failed to insert {} into library! | Err: ",
                game.name
            )
        })?;

        for store in game.stores.iter() {
            sqlx::query(&format!(
                "INSERT INTO stores {} VALUES (?,?,?,?)",
                STORE_INFO_FIELDS
            ))
            .bind(&game.id)
            .bind(&store.name)
            .bind(&store.store_id)
            .bind(&store.store_url)
            .execute(&mut *tx)
            .await
            .with_context(|| {
                "monarch_sql::overwrite_games() Failed to insert game store into stores! | Err: "
            })?;
        }

        sqlx::query(&format!(
            "INSERT INTO properties {} VALUES (?,?,?,?,?,?,?,?,?)",
            MONARCH_GAME_PROPERTIES_FIELDS
        ))
        .bind(&game.id)
        .bind(&game.properties.install_dir)
        .bind(game.properties.size_on_disk as u32)
        .bind(&game.properties.last_played)
        .bind(&game.properties.time_played)
        .bind(&game.properties.description)
        .bind(&game.properties.version)
        .bind(&game.properties.protondb_rating)
        .bind(&game.properties.protondb_url)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            "monarch_sql::overwrite_games() Failed to insert game properties into properties! | Err: "
        })?;
    }

    tx.commit()
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to commit transaction! | Err: ")
}

/// Initiates db, which ensures all tables exist or are created
/// on application launch.
pub async fn init_db(pool: &SqlitePool) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::init_db() Failed to start transaction! | Err: ")?;

    if !table_exists(pool, "library")
        .await
        .with_context(|| "monarch_sql::init_db() -> ")?
    {
        warn!("'library' table not found! Creating new...");

        sqlx::query(&format!(
            "CREATE TABLE IF NOT EXISTS library {}",
            TYPED_MONARCH_GAME_FIELDS
        ))
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::init_db() Failed to verify library table! | Err: ")?;
    }

    if !table_exists(pool, "stores")
        .await
        .with_context(|| "monarch_sql::init_db() -> ")?
    {
        warn!("'stores' table not found! Creating new...");

        sqlx::query(&format!(
            "CREATE TABLE IF NOT EXISTS stores {}",
            TYPED_STORE_INFO_FIELDS
        ))
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::init_db() Failed to verify stores table! | Err: ")?;
    }

    if !table_exists(pool, "properties")
        .await
        .with_context(|| "monarch_sql::init_db() -> ")?
    {
        warn!("'properties' table not found! Creating new...");

        sqlx::query(&format!(
            "CREATE TABLE IF NOT EXISTS properties {}",
            TYPED_MONARCH_GAME_PROPERTIES_FIELDS
        ))
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::init_db() Failed to verify properties table! | Err: ")?;
    }

    tx.commit()
        .await
        .with_context(|| "monarch_sql::init_db() Failed to commit transaction | Err: ")
}

/// Helper function for checking if a tables exists or needs to be created
async fn table_exists(pool: &SqlitePool, name: &str) -> Result<bool> {
    let tables = sqlx::query("SELECT name FROM sqlite_master WHERE type='table' AND name = ? ")
        .bind(name)
        .fetch_all(pool)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::table_exists() Failed to query SQLite for table: {} | Err: ",
                name
            )
        })?;

    Ok(!tables.is_empty())
}
