[package]
name = "monarch_app"
version = "0.2.1"
description = "A FOSS game launcher/manager."
authors = ["an0nymoos3", "sermuns"]
license = "GPL-3.0-or-later"
repository = "https://github.com/Monarch-Launcher/Monarch"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "monarch"
path = "src/main.rs"

[dependencies]
iced = { version = "0.14.0", features = ["image", "svg", "tokio", "canvas"] }
iced_term = "0.7.0"
image = { version = "0.25", features = ["webp"] }
tracing = { version = "0.1.41", features = [
  "max_level_trace",
  "release_max_level_info",
] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
futures = { version = "0.3", default-features = false, features = ["executor"] }
rfd = "0.17.2"
tokio.workspace = true
anyhow = "1.0.86"
chrono = "0.4.43"

monarch_core.workspace = true
monarch_egs.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc = { version = "0.2.7", features = ["exception"] }
