use anyhow::{Context, Result};
use sqlx::{Decode, Encode, FromRow, Row, SqlitePool};
use tracing::{info, warn};

use crate::monarch_games::monarchgame::{MonarchGame, MonarchGameProperties, StoreInfo};

const MONARCH_GAME_FIELDS: &str = "(name, id, executable_path, thumbnail_path, thumbnail_url, launch_args, compatibility, summary, artwork_path, artwork_url, imported, is_installed, managed_by_monarch)";
const TYPED_MONARCH_GAME_FIELDS: &str = "(name TEXT, id TEXT PRIMARY KEY, executable_path TEXT, thumbnail_path TEXT, thumbnail_url TEXT, launch_args TEXT, compatibility TEXT, summary TEXT, artwork_path TEXT, artwork_url TEXT, imported BOOLEAN, is_installed BOOLEAN, managed_by_monarch BOOLEAN)";

const STORE_INFO_FIELDS: &str = "(monarch_game_id, name, store_id, store_url)";
const TYPED_STORE_INFO_FIELDS: &str =
    "(monarch_game_id TEXT PRIMARY KEY, name TEXT, store_id TEXT, store_url TEXT)";

const MONARCH_GAME_PROPERTIES_FIELDS: &str = "(monarch_game_id, install_dir, size_on_disk, last_played, time_played, description, version, protondb_rating, protondb_url, other)";
const TYPED_MONARCH_GAME_PROPERTIES_FIELDS: &str = "(monarch_game_id TEXT PRIMARY KEY, install_dir TEXT, size_on_disk INTEGER, last_played TEXT, time_played TEXT, description TEXT, version TEXT, protondb_rating TEXT, protondb_url TEXT, other TEXT)";

#[derive(Debug, FromRow, Encode, Decode)]
struct MonarchGameRecord {
    pub name: String,
    pub id: String, // Monach ID, generated by monarch-launcher.com
    pub executable_path: Option<String>,
    pub thumbnail_path: String,
    pub thumbnail_url: String,
    pub launch_args: Option<String>,
    pub compatibility: Option<String>,
    pub summary: String,
    pub artwork_path: String,
    pub artwork_url: String,
    pub imported: bool,
    pub is_installed: bool,
    pub managed_by_monarch: bool,
}

#[derive(Debug, FromRow, Encode, Decode)]
#[allow(dead_code)]
struct StoreInfoRecord {
    pub monarch_game_id: String, // Allow dead_code
    pub name: String,
    pub store_id: String,
    pub store_url: String,
}

#[derive(Debug, FromRow, Encode, Decode)]
#[allow(dead_code)]
struct MonarchGamePropertiesRecord {
    pub monarch_game_id: String, // Allow dead_code
    pub install_dir: String,
    pub size_on_disk: u64,
    pub last_played: String,
    pub time_played: String,
    pub description: String,
    pub version: String,

    pub protondb_rating: String,
    pub protondb_url: String,

    pub other: String,
}

impl MonarchGame {
    fn from_sql(
        game_record: MonarchGameRecord,
        store_records: Vec<StoreInfoRecord>,
        properties_record: MonarchGamePropertiesRecord,
    ) -> Self {
        let stores: Vec<StoreInfo> = store_records
            .into_iter()
            .map(|sir| sir.into())
            .collect::<Vec<StoreInfo>>();

        let properties: MonarchGameProperties = properties_record.into();

        Self {
            name: game_record.name,
            id: game_record.id,
            stores,
            executable_path: game_record.executable_path,
            thumbnail_path: game_record.thumbnail_path,
            thumbnail_url: game_record.thumbnail_url,
            launch_args: game_record.launch_args,
            compatibility: game_record.compatibility,
            summary: game_record.summary,
            artwork_path: game_record.artwork_path,
            artwork_url: game_record.artwork_url,
            properties,
            imported: game_record.imported,
            is_installed: game_record.is_installed,
            managed_by_monarch: game_record.managed_by_monarch,
        }
    }
}

impl From<StoreInfoRecord> for StoreInfo {
    fn from(record: StoreInfoRecord) -> Self {
        Self {
            name: record.name,
            store_id: record.store_id,
            store_url: record.store_url,
        }
    }
}

impl From<MonarchGamePropertiesRecord> for MonarchGameProperties {
    fn from(record: MonarchGamePropertiesRecord) -> Self {
        Self {
            install_dir: record.install_dir,
            size_on_disk: record.size_on_disk,
            last_played: record.last_played,
            time_played: record.time_played,
            description: record.description,
            version: record.version,
            protondb_rating: record.protondb_rating,
            protondb_url: record.protondb_url,
            other: serde_json::from_str(&record.other).unwrap_or_default(),
        }
    }
}

/// Fetch all games stores in db, including their properties and storefronts
pub async fn get_library(pool: &SqlitePool) -> Result<Vec<MonarchGame>> {
    // TODO: Use macros for compile-time checks of types/queries?

    let game_records: Vec<MonarchGameRecord> =
        sqlx::query_as::<_, MonarchGameRecord>("SELECT * FROM library")
            .fetch_all(pool)
            .await
            .with_context(|| {
                "monarch_sql::get_library() Failed to fetch_all() MonarchGameRecords! | Err: "
            })?;

    let mut games: Vec<MonarchGame> = Vec::new();
    for game in game_records {
        let stores: Vec<StoreInfoRecord> =
            sqlx::query_as("SELECT * FROM stores WHERE monarch_game_id = ?")
                .bind(&game.id)
                .fetch_all(pool)
                .await
                .with_context(|| {
                    format!(
                        "monarch_sql::get_library() Failed to query StoreInfo for {} | Err: ",
                        &game.name
                    )
                })?;

        let properties: MonarchGamePropertiesRecord =
            sqlx::query_as("SELECT * FROM properties WHERE monarch_game_id = ?")
                .bind(&game.id)
                .fetch_one(pool)
                .await
                .with_context(|| {
                    format!(
                "monarch_sql::get_library() Failed to query MonarchGameProperties for {} | Err: ",
                &game.name
            )
                })?;

        games.push(MonarchGame::from_sql(game, stores, properties));
    }

    Ok(games)
}

/// Insert a single game into the database
pub async fn insert_game(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::insert_game() Failed to start new transaction! | Err: ")?;

    sqlx::query(&format!(
        "INSERT INTO library {} VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
        MONARCH_GAME_FIELDS
    ))
    .bind(&game.name)
    .bind(&game.id)
    .bind(&game.executable_path)
    .bind(&game.thumbnail_path)
    .bind(&game.thumbnail_url)
    .bind(&game.launch_args)
    .bind(&game.compatibility)
    .bind(&game.summary)
    .bind(&game.artwork_path)
    .bind(&game.artwork_url)
    .bind(game.imported)
    .bind(game.is_installed)
    .bind(game.managed_by_monarch)
    .execute(&mut *tx)
    .await
    .with_context(|| "monarch_sql::insert_game() Failed to insert game into library! | Err: ")?;

    for store in game.stores.iter() {
        sqlx::query(&format!(
            "INSERT INTO stores {} VALUES (?,?,?,?)",
            STORE_INFO_FIELDS
        ))
        .bind(&game.id)
        .bind(&store.name)
        .bind(&store.store_id)
        .bind(&store.store_url)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            "monarch_sql::insert_game() Failed to insert game into library! | Err: "
        })?;
    }

    sqlx::query(&format!(
        "INSERT INTO properties {} VALUES (?,?,?,?,?,?,?,?,?,?)",
        MONARCH_GAME_PROPERTIES_FIELDS
    ))
    .bind(&game.id)
    .bind(&game.properties.install_dir)
    .bind(game.properties.size_on_disk as u32)
    .bind(&game.properties.last_played)
    .bind(&game.properties.time_played)
    .bind(&game.properties.description)
    .bind(&game.properties.version)
    .bind(&game.properties.protondb_rating)
    .bind(&game.properties.protondb_url)
    .bind(serde_json::to_string(&game.properties.other).unwrap())
    .execute(&mut *tx)
    .await
    .with_context(|| "monarch_sql::insert_game() Failed to insert game into library! | Err: ")?;

    tx.commit()
        .await
        .with_context(|| "monarch_sql::insert_game() Failed to commit transaction! | Err: ")
}

/// Mark a game as uninstalled by setting is_installed to false
pub async fn mark_game_uninstalled(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    sqlx::query("UPDATE library SET is_installed = false WHERE id = ?")
        .bind(&game.id)
        .execute(pool)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::mark_game_uninstalled() Failed to mark {} as uninstalled! | Err: ",
                &game.name
            )
        })?;

    Ok(())
}

/// Remove all records of a game, including its properties and storefronts
pub async fn remove_game(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::remove_game() Failed to start new transaction! | Err: ")?;

    sqlx::query("DELETE FROM library WHERE id = ?")
        .bind(&game.id)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::remove_game() Failed to remove {} from library table! | Err: ",
                &game.name
            )
        })?;

    sqlx::query("DELETE FROM stores WHERE monarch_game_id = ?")
        .bind(&game.id)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::remove_game() Failed to remove {} from stores table! | Err: ",
                &game.name
            )
        })?;

    sqlx::query("DELETE FROM properties WHERE monarch_game_id = ?")
        .bind(&game.id)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::remove_game() Failed to remove {} from properties table! | Err: ",
                &game.name
            )
        })?;

    tx.commit()
        .await
        .with_context(|| "monarch_sql::remove_game() Failed to commit transaction! | Err: ")
}

/// Update game in db, using Sqlite upserting
pub async fn update_game(pool: &SqlitePool, game: &MonarchGame) -> Result<()> {
    let sql_library_query: String = format!(
        r#"INSERT INTO library{} 
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(id) DO UPDATE SET
        name = ?,
        executable_path = ?,
        thumbnail_path = ?,
        thumbnail_url = ?,
        launch_args = ?,
        compatibility = ?,
        summary = ?,
        artwork_path = ?,
        artwork_url = ?,
        imported = ?,
        is_installed = ?,
        managed_by_monarch = ?"#,
        MONARCH_GAME_FIELDS
    );

    let sql_stores_query: String = format!(
        r#"INSERT INTO stores{} 
    VALUES (?,?,?,?)
    ON CONFLICT(monarch_game_id) DO UPDATE SET
        name = ?,
        store_id = ?,
        store_url = ?
        "#,
        STORE_INFO_FIELDS
    );

    let sql_properties_query: String = format!(
        r#"INSERT INTO properties{} 
    VALUES (?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(monarch_game_id) DO UPDATE SET
        install_dir = ?,
        size_on_disk = ?,
        last_played = ?,
        time_played = ?,
        description = ?,
        version = ?,
        protondb_rating = ?,
        protondb_url = ?,
        other = ?"#,
        MONARCH_GAME_PROPERTIES_FIELDS
    );

    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::update_game() Failed to start transaction! | Err: ")?;

    sqlx::query(&sql_library_query)
        .bind(&game.name)
        .bind(&game.id)
        .bind(&game.executable_path)
        .bind(&game.thumbnail_path)
        .bind(&game.thumbnail_url)
        .bind(&game.launch_args)
        .bind(&game.compatibility)
        .bind(&game.summary)
        .bind(&game.artwork_path)
        .bind(&game.artwork_url)
        .bind(game.imported)
        .bind(game.is_installed)
        .bind(game.managed_by_monarch)
        .bind(&game.name)
        .bind(&game.executable_path)
        .bind(&game.thumbnail_path)
        .bind(&game.thumbnail_url)
        .bind(&game.launch_args)
        .bind(&game.compatibility)
        .bind(&game.summary)
        .bind(&game.artwork_path)
        .bind(&game.artwork_url)
        .bind(game.imported)
        .bind(game.is_installed)
        .bind(game.managed_by_monarch)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::update_game() Failed to upsert {} | Err: ",
                game.name
            )
        })?;

    for store in game.stores.iter() {
        sqlx::query(&sql_stores_query)
            .bind(&game.id)
            .bind(&store.name)
            .bind(&store.store_id)
            .bind(&store.store_url)
            .bind(&store.name)
            .bind(&store.store_id)
            .bind(&store.store_url)
            .execute(&mut *tx)
            .await
            .with_context(|| {
                format!(
                    "monarch_sql::update_game() Failed to upsert {} store! | Err: ",
                    game.name
                )
            })?;
    }

    sqlx::query(&sql_properties_query)
        .bind(&game.id)
        .bind(&game.properties.install_dir)
        .bind(game.properties.size_on_disk as u32)
        .bind(&game.properties.last_played)
        .bind(&game.properties.time_played)
        .bind(&game.properties.description)
        .bind(&game.properties.version)
        .bind(&game.properties.protondb_rating)
        .bind(&game.properties.protondb_url)
        .bind(serde_json::to_string(&game.properties.other).unwrap())
        .bind(&game.properties.install_dir)
        .bind(game.properties.size_on_disk as u32)
        .bind(&game.properties.last_played)
        .bind(&game.properties.time_played)
        .bind(&game.properties.description)
        .bind(&game.properties.version)
        .bind(&game.properties.protondb_rating)
        .bind(&game.properties.protondb_url)
        .bind(serde_json::to_string(&game.properties.other).unwrap())
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::update_game() Failed to upsert {} properties! | Err: ",
                game.name
            )
        })?;

    tx.commit()
        .await
        .with_context(|| "monarch_sql::update_game() Failed to commit transaction! | Err: ")
}

/// Overwrite all games and it's record in the database.
/// Currently done by dropping and refilling all tables.
pub async fn overwrite_games(pool: &SqlitePool, games: &[MonarchGame]) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to start transaction! | Err: ")?;

    sqlx::query("DELETE FROM stores")
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to drop stores! | Err: ")?;

    sqlx::query("DELETE FROM properties")
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to drop properties! | Err: ")?;

    // Have to drop library last due to game.id constraint
    sqlx::query("DELETE FROM library")
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to drop library! | Err: ")?;

    for game in games {
        sqlx::query(&format!(
            "INSERT INTO library {} VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
            MONARCH_GAME_FIELDS
        ))
        .bind(&game.name)
        .bind(&game.id)
        .bind(&game.executable_path)
        .bind(&game.thumbnail_path)
        .bind(&game.thumbnail_url)
        .bind(&game.launch_args)
        .bind(&game.compatibility)
        .bind(&game.summary)
        .bind(&game.artwork_path)
        .bind(&game.artwork_url)
        .bind(game.imported)
        .bind(game.is_installed)
        .bind(game.managed_by_monarch)
        .execute(&mut *tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::overwrite_games() Failed to insert {} into library! | Err: ",
                game.name
            )
        })?;

        for store in game.stores.iter() {
            sqlx::query(&format!(
                "INSERT INTO stores {} VALUES (?,?,?,?)",
                STORE_INFO_FIELDS
            ))
            .bind(&game.id)
            .bind(&store.name)
            .bind(&store.store_id)
            .bind(&store.store_url)
            .execute(&mut *tx)
            .await
            .with_context(|| {
                "monarch_sql::overwrite_games() Failed to insert game store into stores! | Err: "
            })?;
        }

        sqlx::query(&format!(
            "INSERT INTO properties {} VALUES (?,?,?,?,?,?,?,?,?,?)",
            MONARCH_GAME_PROPERTIES_FIELDS
        ))
        .bind(&game.id)
        .bind(&game.properties.install_dir)
        .bind(game.properties.size_on_disk as u32)
        .bind(&game.properties.last_played)
        .bind(&game.properties.time_played)
        .bind(&game.properties.description)
        .bind(&game.properties.version)
        .bind(&game.properties.protondb_rating)
        .bind(&game.properties.protondb_url)
        .bind(serde_json::to_string(&game.properties.other).unwrap())
        .execute(&mut *tx)
        .await
        .with_context(|| {
            "monarch_sql::overwrite_games() Failed to insert game properties into properties! | Err: "
        })?;
    }

    tx.commit()
        .await
        .with_context(|| "monarch_sql::overwrite_games() Failed to commit transaction! | Err: ")
}

/// Initiates db, which ensures all tables exist or are created
/// on application launch.
pub async fn init_db(pool: &SqlitePool) -> Result<()> {
    let mut tx = pool
        .begin()
        .await
        .with_context(|| "monarch_sql::init_db() Failed to start transaction! | Err: ")?;

    if !table_exists(pool, "library")
        .await
        .with_context(|| "monarch_sql::init_db() -> ")?
    {
        warn!("'library' table not found! Creating new...");

        sqlx::query(&format!(
            "CREATE TABLE IF NOT EXISTS library {}",
            TYPED_MONARCH_GAME_FIELDS
        ))
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::init_db() Failed to verify library table! | Err: ")?;
    } else {
        // Migration: Add is_installed column if it doesn't exist
        sqlx::query("ALTER TABLE library ADD COLUMN is_installed BOOLEAN DEFAULT FALSE")
            .execute(&mut *tx)
            .await
            .unwrap_or_default(); // Ignore error if column already exists

        // Migration: Add managed_by_monarch column if it doesn't exist
        sqlx::query("ALTER TABLE library ADD COLUMN managed_by_monarch BOOLEAN DEFAULT FALSE")
            .execute(&mut *tx)
            .await
            .unwrap_or_default(); // Ignore error if column already exists
    }

    if !table_exists(pool, "stores")
        .await
        .with_context(|| "monarch_sql::init_db() -> ")?
    {
        warn!("'stores' table not found! Creating new...");

        sqlx::query(&format!(
            "CREATE TABLE IF NOT EXISTS stores {}",
            TYPED_STORE_INFO_FIELDS
        ))
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::init_db() Failed to verify stores table! | Err: ")?;
    }

    if !table_exists(pool, "properties")
        .await
        .with_context(|| "monarch_sql::init_db() -> ")?
    {
        warn!("'properties' table not found! Creating new...");

        sqlx::query(&format!(
            "CREATE TABLE IF NOT EXISTS properties {}",
            TYPED_MONARCH_GAME_PROPERTIES_FIELDS
        ))
        .execute(&mut *tx)
        .await
        .with_context(|| "monarch_sql::init_db() Failed to verify properties table! | Err: ")?;
    }

    tx.commit()
        .await
        .with_context(|| "monarch_sql::init_db() Failed to commit transaction | Err: ")
}

/// Helper function for checking if a tables exists or needs to be created
async fn table_exists(pool: &SqlitePool, name: &str) -> Result<bool> {
    let tables = sqlx::query("SELECT name FROM sqlite_master WHERE type='table' AND name = ? ")
        .bind(name)
        .fetch_all(pool)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::table_exists() Failed to query SQLite for table: {} | Err: ",
                name
            )
        })?;

    Ok(!tables.is_empty())
}

/// Checks that all tables have correct columns.
/// If not, it adds or removes columns.
///
/// TODO: Implement dropping columns
///
/// NOTE: By reading and doing string manipulations to check for columns
/// you only need to specify them in the constants in the top of the file
/// to allow changes to automatically get migrated.
pub async fn repair_or_migrate_db(pool: &SqlitePool) -> Result<()> {
    /*
     * First fix the library table.
     */

    // Make a vec of pairs, which are the column and column type
    let monarch_games_column_types = TYPED_MONARCH_GAME_FIELDS
        .replace(",", "")
        .replace("(", "")
        .replace(")", "")
        .replace(" PRIMARY KEY", "");
    let monarch_games_column_types_map = monarch_games_column_types
        .split(" ")
        .into_iter()
        .collect::<Vec<&str>>()
        .windows(2)
        .step_by(2)
        .map(|pair| (pair[0].to_string(), pair[1].to_string()))
        .collect::<Vec<(String, String)>>();

    let mut existing_cols: Vec<String> =
        get_existing_columns(pool, "library")
            .await
            .with_context(|| {
                "monarch_sql::repair_or_migrate_db() Failed to get columns in table 'library'"
            })?;

    /*
     * Older Monarch versions could create these tables without a PRIMARY KEY
     * or UNIQUE constraint on their key column. That breaks the ON CONFLICT()
     * upserts used by update_game(), so detect it up front on a committed
     * snapshot (before the transaction starts) so the tables can be rebuilt
     * with the correct schema further down.
     */
    let library_needs_rebuild = !column_is_unique_key(pool, "library", "id")
        .await
        .with_context(|| {
            "monarch_sql::repair_or_migrate_db() Failed to check 'library' key column! | Err: "
        })?;
    let stores_needs_rebuild = !column_is_unique_key(pool, "stores", "monarch_game_id")
        .await
        .with_context(|| {
            "monarch_sql::repair_or_migrate_db() Failed to check 'stores' key column! | Err: "
        })?;
    let mut properties_needs_rebuild =
        !column_is_unique_key(pool, "properties", "monarch_game_id")
            .await
            .with_context(|| {
                "monarch_sql::repair_or_migrate_db() Failed to check 'properties' key column! | Err: "
            })?;

    let mut tx = pool.begin().await.with_context(|| {
        "monarch_sql::repair_or_migrate_db() Failed to start transaction! | Err: "
    })?;

    for col in monarch_games_column_types_map {
        if !existing_cols.contains(&col.0) {
            warn!("{} not found in library!", col.0);
            info!("Creating column: {} in library...", col.0);

            sqlx::query(&format!(
                "ALTER TABLE library ADD COLUMN {} {}",
                col.0, col.1
            ))
            .execute(&mut *tx)
            .await
            .with_context(|| format!("monarch_sql::repair_or_migrate_db() Failed to add column {} to library! | Err: ", col.0))?;
        }
    }

    /*
     * Sanitize NULL values in boolean columns that were added without a
     * DEFAULT clause (e.g. managed_by_monarch), so they decode as false.
     */
    sqlx::query(
        "UPDATE library SET managed_by_monarch = COALESCE(managed_by_monarch, 0)",
    )
    .execute(&mut *tx)
    .await
    .with_context(|| {
        "monarch_sql::repair_or_migrate_db() Failed to sanitize library.managed_by_monarch values! | Err: "
    })?;

    if library_needs_rebuild {
        warn!(
            "monarch_sql::repair_or_migrate_db() 'library' table missing PRIMARY KEY on 'id'! Rebuilding..."
        );
        rebuild_table(&mut tx, "library", TYPED_MONARCH_GAME_FIELDS, MONARCH_GAME_FIELDS)
            .await
            .with_context(|| "monarch_sql::repair_or_migrate_db() -> ")?;
    }

    /*
     * Then fix the stores table.
     */
    let stores_column_types = TYPED_STORE_INFO_FIELDS
        .replace(",", "")
        .replace("(", "")
        .replace(")", "")
        .replace(" PRIMARY KEY", "");
    let stores_column_types_map = stores_column_types
        .split(" ")
        .into_iter()
        .collect::<Vec<&str>>()
        .windows(2)
        .step_by(2)
        .map(|pair| (pair[0].to_string(), pair[1].to_string()))
        .collect::<Vec<(String, String)>>();

    existing_cols = get_existing_columns(pool, "stores")
        .await
        .with_context(|| {
            "monarch_sql::repair_or_migrate_db() Failed to get columns in table 'stores'"
        })?;

    for col in stores_column_types_map {
        if !existing_cols.contains(&col.0) {
            warn!("{} not found in library!", col.0);
            info!("Creating column: {} in store...", col.0);

            sqlx::query(&format!(
                "ALTER TABLE stores ADD COLUMN {} {}",
                col.0, col.1
            ))
            .execute(&mut *tx)
            .await
            .with_context(|| format!("monarch_sql::repair_or_migrate_db() Failed to add column {} to stores! | Err: ", col.0))?;
        }
    }

    if stores_needs_rebuild {
        warn!(
            "monarch_sql::repair_or_migrate_db() 'stores' table missing PRIMARY KEY on 'monarch_game_id'! Rebuilding..."
        );
        rebuild_table(&mut tx, "stores", TYPED_STORE_INFO_FIELDS, STORE_INFO_FIELDS)
            .await
            .with_context(|| "monarch_sql::repair_or_migrate_db() -> ")?;
    }

    /*
     * And lastly fix the properties table.
     */
    let monarch_game_properties_column_types = TYPED_MONARCH_GAME_PROPERTIES_FIELDS
        .replace(",", "")
        .replace("(", "")
        .replace(")", "")
        .replace(" PRIMARY KEY", "");
    let monarch_game_properties_column_types_map = monarch_game_properties_column_types
        .split(" ")
        .into_iter()
        .collect::<Vec<&str>>()
        .windows(2)
        .step_by(2)
        .map(|pair| (pair[0].to_string(), pair[1].to_string()))
        .collect::<Vec<(String, String)>>();

    existing_cols = get_existing_columns(pool, "properties")
        .await
        .with_context(|| {
            "monarch_sql::repair_or_migrate_db() Failed to get columns in table 'stores'"
        })?;

    for col in monarch_game_properties_column_types_map {
        if !existing_cols.contains(&col.0) {
            warn!("{} not found in properties!", col.0);
            info!("Creating column: {} in properties...", col.0);

            sqlx::query(&format!(
                "ALTER TABLE properties ADD COLUMN {} {}",
                col.0, col.1
            ))
            .execute(&mut *tx)
            .await
            .with_context(|| format!("monarch_sql::repair_or_migrate_db() Failed to add column {} to properties! | Err: ", col.0))?;
        }
    }

    /*
     * SQLite does not support changing a column's type with ALTER TABLE,
     * so any type drift must be fixed by rebuilding the table. The old
     * schema declared size_on_disk as TEXT, which breaks u64 decoding.
     */
    let size_on_disk_type = get_column_type(pool, "properties", "size_on_disk")
        .await
        .with_context(|| {
            "monarch_sql::repair_or_migrate_db() Failed to get column type for properties.size_on_disk! | Err: "
        })?;

    if !size_on_disk_type
        .as_deref()
        .map(|t| t.eq_ignore_ascii_case("INTEGER"))
        .unwrap_or(false)
    {
        warn!(
            "properties.size_on_disk declared as {:?}, expected INTEGER. Rebuilding 'properties' table...",
            size_on_disk_type
        );

        sqlx::query("ALTER TABLE properties RENAME TO properties_old")
            .execute(&mut *tx)
            .await
            .with_context(|| {
                "monarch_sql::repair_or_migrate_db() Failed to rename old properties table! | Err: "
            })?;

        sqlx::query(&format!(
            "CREATE TABLE properties {}",
            TYPED_MONARCH_GAME_PROPERTIES_FIELDS
        ))
        .execute(&mut *tx)
        .await
        .with_context(|| {
            "monarch_sql::repair_or_migrate_db() Failed to create new properties table! | Err: "
        })?;

        sqlx::query(&format!(
            "INSERT INTO properties {} SELECT monarch_game_id, install_dir, CAST(size_on_disk AS INTEGER), last_played, time_played, description, version, protondb_rating, protondb_url, other FROM properties_old",
            MONARCH_GAME_PROPERTIES_FIELDS
        ))
        .execute(&mut *tx)
        .await
        .with_context(|| {
            "monarch_sql::repair_or_migrate_db() Failed to migrate properties rows! | Err: "
        })?;

        sqlx::query("DROP TABLE properties_old")
            .execute(&mut *tx)
            .await
            .with_context(|| {
                "monarch_sql::repair_or_migrate_db() Failed to drop old properties table! | Err: "
            })?;

        // The fresh table uses the current schema, which includes the PRIMARY KEY.
        properties_needs_rebuild = false;
    }

    /*
     * Also sanitize rows whose value-level type drifted from the column type
     * (e.g. an empty TEXT written into the INTEGER size_on_disk column by an
     * older app version). This can occur even when the schema is correct.
     */
    sqlx::query(
        "UPDATE properties SET size_on_disk = COALESCE(CAST(size_on_disk AS INTEGER), 0) \
         WHERE typeof(size_on_disk) != 'integer'",
    )
    .execute(&mut *tx)
    .await
    .with_context(|| {
        "monarch_sql::repair_or_migrate_db() Failed to sanitize properties.size_on_disk values! | Err: "
    })?;

    if properties_needs_rebuild {
        warn!(
            "monarch_sql::repair_or_migrate_db() 'properties' table missing PRIMARY KEY on 'monarch_game_id'! Rebuilding..."
        );
        rebuild_table(
            &mut tx,
            "properties",
            TYPED_MONARCH_GAME_PROPERTIES_FIELDS,
            MONARCH_GAME_PROPERTIES_FIELDS,
        )
        .await
        .with_context(|| "monarch_sql::repair_or_migrate_db() -> ")?;
    }

    tx.commit().await.with_context(|| {
        "monarch_sql::repair_or_migrate_db() Failed to commit transaction | Err: "
    })?;

    Ok(())
}

/// Fetches all column names for a given table
async fn get_existing_columns(pool: &SqlitePool, table_name: &str) -> Result<Vec<String>> {
    let cols = sqlx::query_scalar::<_, String>(&format!(
        "SELECT name FROM pragma_table_info('{}')",
        table_name
    ))
    .fetch_all(pool)
    .await
    .with_context(|| format!("Failed to read columns for table '{}'", table_name))?;

    Ok(cols)
}

/// Fetches the declared type of a single column in a table.
/// Used to detect schema mismatches that `ALTER TABLE ADD COLUMN` cannot fix.
async fn get_column_type(
    pool: &SqlitePool,
    table_name: &str,
    column_name: &str,
) -> Result<Option<String>> {
    let rows = sqlx::query(&format!("PRAGMA table_info('{}')", table_name))
        .fetch_all(pool)
        .await
        .with_context(|| format!("Failed to read column types for table '{}'", table_name))?;

    for row in rows {
        let name: String = row.get(1);
        if name == column_name {
            return Ok(Some(row.get::<String, _>(2)));
        }
    }

    Ok(None)
}

/// Checks whether a table constrains the given column with a PRIMARY KEY or
/// a single-column UNIQUE index, as required by the ON CONFLICT() upserts.
async fn column_is_unique_key(
    pool: &SqlitePool,
    table_name: &str,
    column_name: &str,
) -> Result<bool> {
    // A PRIMARY KEY constraint shows up in PRAGMA table_info with pk > 0.
    let table_info = sqlx::query(&format!("PRAGMA table_info('{}')", table_name))
        .fetch_all(pool)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::column_is_unique_key() Failed to read columns for table '{}' | Err: ",
                table_name
            )
        })?;

    for row in &table_info {
        let name: String = row.get(1);
        let primary_key_position: i32 = row.get(5);
        if name == column_name && primary_key_position > 0 {
            return Ok(true);
        }
    }

    // A UNIQUE index also satisfies ON CONFLICT, but only when it covers
    // exactly the conflict target column.
    let indexes = sqlx::query(&format!("PRAGMA index_list('{}')", table_name))
        .fetch_all(pool)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::column_is_unique_key() Failed to read indexes for table '{}' | Err: ",
                table_name
            )
        })?;

    for index in &indexes {
        let unique: i32 = index.get(2);
        if unique == 0 {
            continue;
        }
        let index_name: String = index.get(1);
        let index_columns = sqlx::query(&format!("PRAGMA index_info('{}')", index_name))
            .fetch_all(pool)
            .await
            .with_context(|| {
                format!(
                    "monarch_sql::column_is_unique_key() Failed to read index '{}' | Err: ",
                    index_name
                )
            })?;

        if index_columns.len() == 1 {
            let name: String = index_columns[0].get(2);
            if name == column_name {
                return Ok(true);
            }
        }
    }

    Ok(false)
}

/// Rebuilds a table with the given (current) schema, preserving all existing
/// rows. Used to restore PRIMARY KEY / UNIQUE constraints that older Monarch
/// versions left out, which otherwise break every ON CONFLICT upsert.
async fn rebuild_table(
    tx: &mut sqlx::Transaction<'_, sqlx::Sqlite>,
    table_name: &str,
    typed_fields: &str,
    fields: &str,
) -> Result<()> {
    let old_table = format!("{}_old", table_name);
    let column_list = fields.trim_start_matches('(').trim_end_matches(')');

    sqlx::query(&format!("ALTER TABLE {} RENAME TO {}", table_name, old_table))
        .execute(&mut **tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::rebuild_table() Failed to rename old {} table! | Err: ",
                table_name
            )
        })?;

    sqlx::query(&format!("CREATE TABLE {} {}", table_name, typed_fields))
        .execute(&mut **tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::rebuild_table() Failed to create new {} table! | Err: ",
                table_name
            )
        })?;

    sqlx::query(&format!(
        "INSERT INTO {} ({}) SELECT {} FROM {}",
        table_name, column_list, column_list, old_table
    ))
    .execute(&mut **tx)
    .await
    .with_context(|| {
        format!(
            "monarch_sql::rebuild_table() Failed to migrate {} rows! | Err: ",
            table_name
        )
    })?;

    sqlx::query(&format!("DROP TABLE {}", old_table))
        .execute(&mut **tx)
        .await
        .with_context(|| {
            format!(
                "monarch_sql::rebuild_table() Failed to drop old {} table! | Err: ",
                table_name
            )
        })?;

    Ok(())
}
