use anyhow::{bail, Context, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use tauri::AppHandle;
use tracing::error;

use super::games::GameType;
use super::stores::StoreType;
use crate::monarch_games::games::SearchResult;
use crate::monarch_games::legendary_client::LegendaryClient;
use crate::monarch_games::monarch_client::MonarchClient;
use crate::monarch_games::steam_client::SteamClient;
use crate::monarch_utils::monarch_download::download_image;
use crate::monarch_utils::monarch_fs::path_exists;
use crate::monarch_utils::monarch_state::MONARCH_STATE;

#[cfg(target_os = "linux")]
use crate::monarch_games::linux::umu::umu_run;

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct MonarchGame {
    pub name: String,
    pub id: String, // Monach ID, generated by monarch-launcher.com
    pub platform: String,
    pub platform_id: String,
    pub executable_path: String,
    pub thumbnail_path: String,
    pub thumbnail_url: String,
    pub launch_args: String,
    pub compatibility: String,
    pub store_page: String,
    pub description: String,

    #[serde(default)]
    pub install_dir: String,

    #[serde(default)]
    pub summary: String,

    #[serde(default)]
    pub artwork_path: String,
    pub artwork_url: String,

    // Technical fields for game details
    #[serde(default)]
    pub install_size: String,

    #[serde(default)]
    pub last_played: String,

    #[serde(default)]
    pub play_time: String,

    #[serde(default)]
    pub version: String,
}

impl MonarchGame {
    pub fn new(
        name: &str,
        id: i32,
        platform: &str,
        platform_id: &str,
        store_page: &str,
        exec_path: &str,
        thumbnail_path: &str,
    ) -> Self {
        Self {
            name: name.to_string(),
            id: id.to_string(),
            platform: platform.to_string(),
            platform_id: platform_id.to_string(),
            executable_path: exec_path.to_string(),
            thumbnail_path: thumbnail_path.to_string(),
            thumbnail_url: String::new(),
            launch_args: String::new(),
            compatibility: String::new(),
            store_page: store_page.to_string(),
            install_dir: String::new(),
            summary: String::new(),
            artwork_url: String::new(),
            artwork_path: String::new(),
            install_size: String::new(),
            last_played: String::new(),
            play_time: String::new(),
            version: String::new(),
        }
    }

    /// Download thumbnail for MonarchGame
    pub async fn download_thumbnail(&self) -> Result<()> {
        let path: PathBuf = PathBuf::from(&self.thumbnail_path);

        if path_exists(&path) {
            return Ok(());
        }

        download_image(&self.thumbnail_url, &path)
            .await
            .with_context(|| "monarchgame::download_thumbnail() -> ")?;
        Ok(())
    }

    /// Download thumbnail for MonarchGame
    pub async fn download_artwork(&self) -> Result<()> {
        let path: PathBuf = PathBuf::from(&self.artwork_path);

        if path_exists(&path) {
            return Ok(());
        }

        download_image(&self.artwork_url, &path)
            .await
            .with_context(|| "monarchgame::download_thumbnail() -> ")?;
        Ok(())
    }

    /// Randomly generates a Monarch ID
    pub fn manually_generate_id(&mut self) {
        let mut id: String = format!("MONARCH-{}", rand::random::<u32>());
        match MONARCH_STATE.read() {
            Ok(state) => {
                while state.binary_game_id_collision(&id) {
                    id = format!("MONARCH-{}", rand::random::<u32>());
                }
                self.id = id;
            }
            Err(e) => {
                error!(
                    "monarchgame::download_thumbnail() Failed to lock on MONARCH_STATE | Err: {}",
                    e
                )
            }
        }
    }

    pub fn is_installed(&self) -> bool {
        if let Ok(state) = MONARCH_STATE.read() {
            return state.get_game(&self.id).is_some();
        }
        false
    }

    /// Convert MonarchWebGame to MonarchGame
    pub fn from(other: &MonarchWebApiGame) -> Self {
        Self {
            name: other.name.to_string(),
            id: other.id.to_string(),
            platform: "".to_string(),
            platform_id: "".to_string(),
            executable_path: "".to_string(),
            thumbnail_path: other.thumbnail_path.to_string(),
            thumbnail_url: other.cover_url.to_string(),
            launch_args: "".to_string(),
            compatibility: "".to_string(),
            store_page: "".to_string(),
            install_dir: "".to_string(),
            summary: other.summary.clone(),
            artwork_url: other.artwork_url.clone(),
            artwork_path: "".to_string(),
            install_size: "Unknown".to_string(),
            last_played: "Never".to_string(),
            play_time: "0 hours".to_string(),
            version: "Unknown".to_string(),
        }
    }
}

#[async_trait]
impl GameType for MonarchGame {
    fn get_name(&self) -> String {
        self.name.clone()
    }

    fn get_platform(&self) -> Box<dyn StoreType> {
        match self.platform.as_str() {
            "monarch" => Box::new(MonarchClient::new()),
            "steam" => Box::new(SteamClient::new()),
            "steamcmd" => Box::new(SteamClient::new()),
            "epic" => Box::new(LegendaryClient::new()),
            _ => {
                panic!("Invalid platform: {}", self.platform)
            }
        }
    }

    fn get_platform_id(&self) -> String {
        self.platform_id.clone()
    }

    fn get_description(&self) -> String {
        unimplemented!()
    }

    fn get_price(&self) -> f64 {
        0.0
    }

    async fn launch(&self) -> Result<()> {
        let game: MonarchGame = match MONARCH_STATE.read() {
            Ok(state) => match state.get_game(&self.id) {
                Some(game) => game,
                None => {
                    bail!("monarchgame::launch() -> Game not found");
                }
            },
            Err(e) => {
                bail!(
                    "monarchgame::launch() Failed to lock on MONARCH_STATE | Err: {}",
                    e
                );
            }
        };

        #[cfg(target_os = "linux")]
        {
            if !game.executable_path.is_empty() {
                return umu_run(handle, &game)
                    .await
                    .with_context(|| "monarchgame::launch() -> ");
            }

            if game.compatibility.contains("UMU") {
                return umu_run(handle, &game)
                    .await
                    .with_context(|| "monarchgame::launch() -> ");
            }
        }

        game.get_platform()
            .launch_game(handle, &game)
            .await
            .with_context(|| "monarchgame::launch() -> ")
    }

    fn into_monarchgame(&self) -> MonarchGame {
        self.clone()
    }
}

impl PartialEq for MonarchGame {
    fn eq(&self, other: &Self) -> bool {
        let platform = match self.platform.as_str() {
            "steamcmd" => "steam",
            _ => &self.platform,
        };

        let other_platform = match other.platform.as_str() {
            "steamcmd" => "steam",
            _ => &other.platform,
        };

        self.platform_id == other.platform_id && platform == other_platform
    }
}

impl Eq for MonarchGame {}

/// Struct representation of games returned from monarch-launcher.com
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MonarchWebApiGame {
    pub name: String,
    pub id: String,
    pub igdb_id: i32,
    pub cover_url: String,
    pub artwork_url: String,
    pub summary: String,
    pub platforms: Vec<MonarchWebApiPlatform>,

    #[serde(default)]
    pub thumbnail_path: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MonarchWebApiPlatform {
    pub name: String,
    pub platform_id: String,
    pub store_page: String,
}

pub enum GameImageType {
    Cover,
    Artwork,
}

impl SearchResult for MonarchWebApiGame {
    fn to_search_result(&self) -> MonarchWebApiGame {
        return self.clone();
    }

    fn into_monarchgame(&self) -> MonarchGame {
        MonarchGame::from(self)
    }
}

impl MonarchWebApiGame {
    pub fn from_monarchgame(monarch_game: MonarchGame) -> Self {
        let platform: MonarchWebApiPlatform;

        match monarch_game.platform.as_str() {
            "steam" => {
                platform = MonarchWebApiPlatform {
                    name: "steam".to_string(),
                    platform_id: monarch_game.platform_id,
                    store_page: monarch_game.store_page,
                }
            }
            _ => {
                panic!("Unknown platform: {}", monarch_game.platform)
            }
        }

        Self {
            name: monarch_game.name,
            id: monarch_game.id,
            igdb_id: -1,
            cover_url: monarch_game.thumbnail_url,
            artwork_url: "".to_string(),
            summary: monarch_game.description,
            platforms: vec![platform],
            thumbnail_path: monarch_game.thumbnail_path,
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct MonarchGameProperties {
    pub name: String,
    pub platform: String,
    pub platform_id: String,
    pub install_dir: String,
    pub size_on_disk: String,
    pub last_played: String,
    pub time_played: String,
    pub description: String,

    pub protondb_rating: String,
    pub protondb_url: String,
}

impl Default for MonarchGameProperties {
    fn default() -> Self {
        Self {
            name: "Error".to_string(),
            platform: "Error".to_string(),
            platform_id: "Error".to_string(),
            install_dir: "Error".to_string(),
            size_on_disk: "Error".to_string(),
            last_played: "Error".to_string(),
            time_played: "WIP".to_string(),
            description: "Error".to_string(),
            protondb_rating: "N/A".to_string(),
            protondb_url: "".to_string(),
        }
    }
}
