use anyhow::{bail, Context, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use tracing::error;

use super::games::GameType;
use super::stores::StoreType;
use crate::monarch_games::games::SearchResult;
use crate::monarch_games::legendary_client::LegendaryClient;
use crate::monarch_games::monarch_client::MonarchClient;
use crate::monarch_games::steam_client::SteamClient;
use crate::monarch_utils::monarch_download::download_image;
use crate::monarch_utils::monarch_fs::path_exists;
use crate::monarch_utils::monarch_state::MONARCH_STATE;

#[cfg(target_os = "linux")]
use crate::monarch_games::linux::umu::umu_run;

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct MonarchGame {
    pub name: String,
    pub id: String, // Monach ID, generated by monarch-launcher.com
    pub stores: Vec<StoreInfo>,
    pub executable_path: String,
    pub thumbnail_path: String,
    pub thumbnail_url: String,
    pub launch_args: String,
    pub compatibility: String,
    pub store_page: String,

    #[serde(default)]
    pub summary: String,

    #[serde(default)]
    pub artwork_path: String,
    pub artwork_url: String,

    #[serde(default)]
    pub properties: MonarchGameProperties,
}

impl MonarchGame {
    pub fn new(
        name: &str,
        id: i32,
        store: &str,
        store_id: &str,
        store_page: &str,
        exec_path: &str,
        thumbnail_path: &str,
    ) -> Self {
        Self {
            name: name.to_string(),
            id: id.to_string(),
            stores: vec![StoreInfo {
                name: store.to_string(),
                store_id: store_id.to_string(),
                store_url: "".to_string(),
            }],
            executable_path: exec_path.to_string(),
            thumbnail_path: thumbnail_path.to_string(),
            thumbnail_url: String::new(),
            launch_args: String::new(),
            compatibility: String::new(),
            store_page: store_page.to_string(),
            summary: String::new(),
            artwork_url: String::new(),
            artwork_path: String::new(),
            properties: MonarchGameProperties::default(),
        }
    }

    /// Download thumbnail for MonarchGame
    pub async fn download_thumbnail(&self) -> Result<()> {
        let path: PathBuf = PathBuf::from(&self.thumbnail_path);

        if path_exists(&path) {
            return Ok(());
        }

        download_image(&self.thumbnail_url, &path)
            .await
            .with_context(|| "monarchgame::download_thumbnail() -> ")?;
        Ok(())
    }

    /// Download thumbnail for MonarchGame
    pub async fn download_artwork(&self) -> Result<()> {
        let path: PathBuf = PathBuf::from(&self.artwork_path);

        if path_exists(&path) {
            return Ok(());
        }

        download_image(&self.artwork_url, &path)
            .await
            .with_context(|| "monarchgame::download_thumbnail() -> ")?;
        Ok(())
    }

    /// Randomly generates a Monarch ID
    pub fn manually_generate_id(&mut self) {
        let mut id: String = format!("MONARCH-{}", rand::random::<u32>());
        match MONARCH_STATE.read() {
            Ok(state) => {
                while state.binary_game_id_collision(&id) {
                    id = format!("MONARCH-{}", rand::random::<u32>());
                }
                self.id = id;
            }
            Err(e) => {
                error!(
                    "monarchgame::download_thumbnail() Failed to lock on MONARCH_STATE | Err: {}",
                    e
                )
            }
        }
    }

    pub fn is_installed(&self) -> bool {
        if let Ok(state) = MONARCH_STATE.read() {
            return state.get_game(&self.id).is_some();
        }
        false
    }

    /// Convert MonarchWebGame to MonarchGame
    pub fn from(other: &MonarchWebApiGame) -> Self {
        Self {
            name: other.name.to_string(),
            id: other.id.to_string(),
            stores: other.platforms.iter().map(StoreInfo::from).collect(),
            executable_path: "".to_string(),
            thumbnail_path: other.thumbnail_path.to_string(),
            thumbnail_url: other.cover_url.to_string(),
            launch_args: "".to_string(),
            compatibility: "".to_string(),
            store_page: "".to_string(),
            summary: other.summary.clone(),
            artwork_url: other.artwork_url.clone(),
            artwork_path: "".to_string(),
            properties: MonarchGameProperties::default(),
        }
    }
}

#[async_trait]
impl GameType for MonarchGame {
    fn get_name(&self) -> String {
        self.name.clone()
    }

    fn get_store(&self) -> Box<dyn StoreType> {
        match self.stores[0].name.as_str() {
            "monarch" => Box::new(MonarchClient::new()),
            "steam" => Box::new(SteamClient::new()),
            "steamcmd" => Box::new(SteamClient::new()),
            "epic" => Box::new(LegendaryClient::new()),
            _ => {
                panic!("Invalid platform: {:?}", self.stores)
            }
        }
    }

    fn get_store_name(&self) -> String {
        if self.stores.is_empty() {
            return "".to_string();
        }
        self.stores[0].name.clone()
    }

    fn get_store_id(&self) -> String {
        if self.stores.is_empty() {
            return "".to_string();
        }
        self.stores[0].store_id.clone()
    }

    fn get_description(&self) -> String {
        unimplemented!()
    }

    fn get_price(&self) -> f64 {
        0.0
    }

    async fn launch(&self) -> Result<()> {
        let game: MonarchGame = match MONARCH_STATE.read() {
            Ok(state) => match state.get_game(&self.id) {
                Some(game) => game,
                None => {
                    bail!("monarchgame::launch() -> Game not found");
                }
            },
            Err(e) => {
                bail!(
                    "monarchgame::launch() Failed to lock on MONARCH_STATE | Err: {}",
                    e
                );
            }
        };

        #[cfg(target_os = "linux")]
        {
            if !game.executable_path.is_empty() {
                return umu_run(&game)
                    .await
                    .with_context(|| "monarchgame::launch() -> ");
            }

            if game.compatibility.contains("UMU") {
                return umu_run(&game)
                    .await
                    .with_context(|| "monarchgame::launch() -> ");
            }
        }

        game.get_store()
            .launch_game(&game)
            .await
            .with_context(|| "monarchgame::launch() -> ")
    }

    fn into_monarchgame(&self) -> MonarchGame {
        self.clone()
    }
}

impl PartialEq for MonarchGame {
    fn eq(&self, other: &Self) -> bool {
        if self.stores.is_empty() || other.stores.is_empty() {
            return false;
        }

        let store: &str = match self.stores[0].name.as_str() {
            "steamcmd" => "steam",
            _ => &self.stores[0].name,
        };
        let store_id: &str = &self.stores[0].store_id;

        let other_store: &str = match other.stores[0].name.as_str() {
            "steamcmd" => "steam",
            _ => &other.stores[0].name,
        };
        let other_store_id: &str = &other.stores[0].store_id;

        store_id == other_store_id && store == other_store
    }
}

impl Eq for MonarchGame {}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoreInfo {
    pub(crate) name: String,
    pub(crate) store_id: String,
    pub(crate) store_url: String,
}

impl From<MonarchWebApiPlatform> for StoreInfo {
    fn from(value: MonarchWebApiPlatform) -> Self {
        Self {
            name: value.name,
            store_id: value.platform_id,
            store_url: value.store_page,
        }
    }
}

impl From<&MonarchWebApiPlatform> for StoreInfo {
    fn from(value: &MonarchWebApiPlatform) -> Self {
        Self {
            name: value.name.to_string(),
            store_id: value.platform_id.to_string(),
            store_url: value.store_page.to_string(),
        }
    }
}

/// Struct representation of games returned from monarch-launcher.com
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MonarchWebApiGame {
    pub name: String,
    pub id: String,
    pub igdb_id: i32,
    pub cover_url: String,
    pub artwork_url: String,
    pub summary: String,
    pub platforms: Vec<MonarchWebApiPlatform>,

    #[serde(default)]
    pub thumbnail_path: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MonarchWebApiPlatform {
    pub name: String,
    pub platform_id: String,
    pub store_page: String,
}

pub enum GameImageType {
    Cover,
    Artwork,
}

impl SearchResult for MonarchWebApiGame {
    fn to_search_result(&self) -> MonarchWebApiGame {
        return self.clone();
    }

    fn into_monarchgame(&self) -> MonarchGame {
        MonarchGame::from(self)
    }
}

impl MonarchWebApiGame {
    pub fn from_monarchgame(monarch_game: MonarchGame) -> Self {
        Self {
            name: monarch_game.name,
            id: monarch_game.id,
            igdb_id: -1,
            cover_url: monarch_game.thumbnail_url,
            artwork_url: "".to_string(),
            summary: monarch_game.summary,
            platforms: monarch_game
                .stores
                .iter()
                .map(MonarchWebApiPlatform::from)
                .collect(),
            thumbnail_path: monarch_game.thumbnail_path,
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MonarchGameProperties {
    pub install_dir: String,
    pub size_on_disk: u64,
    pub last_played: String,
    pub time_played: String,
    pub description: String,
    pub version: String,

    pub protondb_rating: String,
    pub protondb_url: String,
}

impl Default for MonarchGameProperties {
    fn default() -> Self {
        Self {
            install_dir: "Error".to_string(),
            size_on_disk: 0,
            last_played: "".to_string(),
            time_played: "WIP".to_string(),
            description: "Error".to_string(),
            version: "Error".to_string(),
            protondb_rating: "N/A".to_string(),
            protondb_url: "".to_string(),
        }
    }
}

impl From<StoreInfo> for MonarchWebApiPlatform {
    fn from(value: StoreInfo) -> Self {
        Self {
            name: value.name,
            platform_id: value.store_id,
            store_page: value.store_url,
        }
    }
}

impl From<&StoreInfo> for MonarchWebApiPlatform {
    fn from(value: &StoreInfo) -> Self {
        Self {
            name: value.name.to_string(),
            platform_id: value.store_id.to_string(),
            store_page: value.store_url.to_string(),
        }
    }
}
