use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

use crate::monarch_utils::monarch_download::download_image;
use crate::monarch_utils::monarch_fs::path_exists;
use crate::monarch_utils::monarch_state::MONARCH_STATE;

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct MonarchGame {
    pub name: String,
    pub id: String, // Monach ID, generated by monarch-launcher.com
    pub platform: String,
    pub platform_id: String,
    pub executable_path: String,
    pub thumbnail_path: String,
    pub thumbnail_url: String,
    pub launch_args: String,
    pub compatibility: String,
    pub store_page: String,

    #[serde(default)]
    pub install_dir: String,

    #[serde(default)]
    pub summary: String,

    #[serde(default)]
    pub artwork_path: String,
    pub artwork_url: String,

    // Technical fields for game details
    #[serde(default)]
    pub install_size: String,

    #[serde(default)]
    pub last_played: String,

    #[serde(default)]
    pub play_time: String,

    #[serde(default)]
    pub version: String,
}

impl MonarchGame {
    pub fn new(
        name: &str,
        id: i32,
        platform: &str,
        platform_id: &str,
        store_page: &str,
        exec_path: &str,
        thumbnail_path: &str,
    ) -> Self {
        Self {
            name: name.to_string(),
            id: id.to_string(),
            platform: platform.to_string(),
            platform_id: platform_id.to_string(),
            executable_path: exec_path.to_string(),
            thumbnail_path: thumbnail_path.to_string(),
            thumbnail_url: String::new(),
            launch_args: String::new(),
            compatibility: String::new(),
            store_page: store_page.to_string(),
            install_dir: String::new(),
            summary: String::new(),
            artwork_url: String::new(),
            artwork_path: String::new(),
            install_size: String::new(),
            last_played: String::new(),
            play_time: String::new(),
            version: String::new(),
        }
    }

    /// Download thumbnail for MonarchGame
    pub async fn download_thumbnail(&self) -> Result<()> {
        let path: PathBuf = PathBuf::from(&self.thumbnail_path);

        if path_exists(&path) {
            return Ok(());
        }

        download_image(&self.thumbnail_url, &path)
            .await
            .with_context(|| "monarchgame::download_thumbnail() -> ")?;
        Ok(())
    }

    /// Download thumbnail for MonarchGame
    pub async fn download_artwork(&self) -> Result<()> {
        let path: PathBuf = PathBuf::from(&self.artwork_path);

        if path_exists(&path) {
            return Ok(());
        }

        download_image(&self.artwork_url, &path)
            .await
            .with_context(|| "monarchgame::download_thumbnail() -> ")?;
        Ok(())
    }

    /// Randomly generates a Monarch ID
    pub fn manually_generate_id(&mut self) {
        let mut id: String = format!("MONARCH-{}", rand::random::<u32>());
        unsafe {
            while MONARCH_STATE.binary_game_id_collision(&id) {
                id = format!("MONARCH-{}", rand::random::<u32>());
            }
        }
        self.id = id;
    }

    /// Convert MonarchWebGame to MonarchGame
    pub fn from(other: &MonarchWebGame) -> Self {
        Self {
            name: other.name.to_string(),
            id: other.id.to_string(),
            platform: other.platform.to_string(),
            platform_id: other.platform_id.to_string(),
            executable_path: "".to_string(),
            thumbnail_path: "".to_string(),
            thumbnail_url: other.cover_url.to_string(),
            launch_args: "".to_string(),
            compatibility: "".to_string(),
            store_page: other.store_page.to_string(),
            install_dir: "".to_string(),
            summary: other.summary.clone(),
            artwork_url: other.artwork_url.clone(),
            artwork_path: "".to_string(),
            install_size: "Unknown".to_string(),
            last_played: "Never".to_string(),
            play_time: "0 hours".to_string(),
            version: "Unknown".to_string(),
        }
    }
}

impl PartialEq for MonarchGame {
    fn eq(&self, other: &Self) -> bool {
        let platform = match self.platform.as_str() {
            "steamcmd" => "steam",
            _ => &self.platform,
        };

        let other_platform = match other.platform.as_str() {
            "steamcmd" => "steam",
            _ => &other.platform,
        };

        self.platform_id == other.platform_id && platform == other_platform
    }
}

impl Eq for MonarchGame {}

/// Struct representation of games returned from monarch-launcher.com
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MonarchWebGame {
    pub name: String,
    pub id: String,
    pub igdb_id: i32,
    pub cover_url: String,
    pub artwork_url: String,
    pub summary: String,
    pub platform: String,
    pub platform_id: String,
    pub store_page: String,
}

pub enum GameImageType {
    Cover,
    Artwork,
}
