export const colors = {
  white: '#FFFFFF',
  black: '#0E0E12',
  surface: '#1C1C24',
  surfaceElevated: '#28283A',
  lightgreen: '#14CA26',
  darkgreen: '#0E8628',
  primary: '#FA5002',
  secondary: '#3A3A48',
  error: '#FF3333',
  background: '#0E0E12',
  textPrimary: '#FFFFFF',
  textSecondary: '#9090A0',
  border: '#3A3A48',
  borderLight: '#2A2A35',
  glowOrange: 'rgba(250, 80, 2, 0.3)',
  button: {
    primary: {
      text: '#0E0E12',
      border: '#FA5002',
      background: '#FA5002',
      hoverBorder: '#FF6B2C',
      hoverText: '#000000',
      hoverBackground: '#FF6B2C',
      focusText: '#000000',
      focusBorder: '#FF4500',
      focusBackground: '#FF4500',
      active: '',
      disabled: {
        text: '#454545',
        border: '#FF6000',
        background: '#666',
        hoverBorder: '#666',
        hoverText: '#FFF',
        hoverBackground: '',
      },
    },
    secondary: {
      text: '#FA5002',
      border: '#1C1C24',
      background: '#1C1C24',
      hoverBorder: '#28283A',
      hoverText: '#FF6B2C',
      hoverBackground: '#28283A',
      focusText: '#FA5002',
      focusBorder: '#28283A',
      focusBackground: '#28283A',
      active: '',
      disabled: {
        text: '#454545',
        border: '#FF6000',
        background: '#FF6000',
        hoverBorder: '#454545',
        hoverText: '#FFF',
        hoverBackground: '',
      },
    },
    menu: {
      text: '#FA5002',
      border: 'transparent',
      background: 'transparent',
      hoverBorder: 'transparent',
      hoverText: '#FF6B2C',
      hoverBackground: '#28283A',
      focusText: '#FA5002',
      focusBorder: 'transparent',
      focusBackground: 'transparent',
      active: '#28283A',
      disabled: {
        text: '',
        border: '',
        background: '',
        hoverBorder: '',
        hoverText: '',
        hoverBackground: '',
      },
    },
    icon: {
      text: '',
      border: 'transparent',
      background: 'transparent',
      hoverBorder: 'transparent',
      hoverText: 'transparent',
      hoverBackground: 'transparent',
      focusText: 'transparent',
      focusBorder: 'transparent',
      focusBackground: 'transparent',
      active: 'transparent',
      disabled: {
        text: '',
        border: '',
        background: '',
        hoverBorder: '',
        hoverText: '',
        hoverBackground: '',
      },
    },
    danger: {
      text: '#FFF',
      border: '#FF3333',
      background: '#FF3333',
      hoverBorder: '#FD1111',
      hoverText: '#FFF',
      hoverBackground: '#FD1111',
      focusText: '#FFF',
      focusBorder: '#FD1111',
      focusBackground: '#FD1111',
      active: '#FD1111',
      disabled: {
        text: '',
        border: '',
        background: '',
        hoverBorder: '',
        hoverText: '',
        hoverBackground: '',
      },
    },
  },
};

export type ButtonVariant = typeof colors.button;

type Theme = {
  colors: typeof colors;
};

const theme: Theme = {
  colors,
};

export default theme;
