[package]
name = "monarch_egs"
version = "0.1.0"
edition = "2024"

[build-dependencies]
dotenv = "0.15.0"

[dependencies]
reqwest = { version = "0.13", features = ["json", "form"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2"
