name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-24.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-24.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libappindicator3-dev librsvg2-dev patchelf

      # If tagName and releaseId are omitted tauri-action will only build the app and won't try to upload any assets.
      - name: build
        env:
          MONARCH_URL: https://monarch-launcher.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          cargo build --release ${{ matrix.args }}

      - name: determine artifact name
        id: artifact_name
        run: |
          if [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            echo "name=monarch-${{ github.event.inputs.version }}-macos-${{ matrix.args == '--target aarch64-apple-darwin' && 'arm64' || 'x64' }}" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.platform }}" == "ubuntu-24.04" ]]; then
            echo "name=monarch-${{ github.event.inputs.version }}-linux-x64" >> $GITHUB_OUTPUT
          else
            echo "name=monarch-${{ github.event.inputs.version }}-windows-x64" >> $GITHUB_OUTPUT
          fi

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.name }}
          path: target/${{ matrix.args && 'aarch64-apple-darwin/' || '' }}release/

      - name: create release
        if: matrix.platform == 'ubuntu-24.04'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: monarch-v__VERSION__
          name: 'Monarch v__VERSION__'
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}